meme_zone_frontend/app.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_wtf.csrf import CSRFProtect
from routes import *


app = Flask("__name__")

app.secret_key = "numberforsecret1234509876"
csrf_token = CSRFProtect(app)
app.register_blueprint(routes)
Bootstrap(app)

if __name__ == "__main__":
    app.run(debug=True)


meme_zone_frontend/routes/__init__.py
from flask import Blueprint

routes = Blueprint("routes", __name__, static_folder="static", template_folder="templates")

from .meme_stream import *

meme_zone_frontend/routes/meme_stream.py
import json
import uuid
import pandas as pd
import requests
from flask import Flask, render_template, request, redirect, url_for, jsonify
from libs.uploader_form import meme_info
from libs.start_page import start_proc
from flask import Flask, render_template, flash, request
from wtforms import Form, TextField, validators, SubmitField, TextAreaField
from datetime import datetime

from . import routes as app


@app.errorhandler(404)
def not_found(e): 
    return render_template("404.html") 

@app.route("/start", methods=["GET", "POST"])
def start_page():
    if request.method == "POST":
        form = start_proc()
        render_template("start.html", form=form)
        if request.form.get("submit_btn") == "upload":
            return redirect(url_for("routes.memes", start_page_var="True"))
        elif request.form.get("submit_btn") == "view":
            return redirect(url_for("routes.memes", start_page_var="False"))
        else:
            pass
    else:
        form = start_proc()
        return render_template("start.html", form=form)


@app.route("/", methods=["POST", "GET"])
@app.route("/memes", methods=["POST", "GET"])
def memes():
    form = meme_info()
    if request.method == "POST":
        if form.validate_on_submit():
            uploader_name = form["uploader_name"].data
            meme_caption = form["meme_caption"].data
            meme_url = form["meme_url"].data
            another_entry_cb = form["another_entry_cb"].data

            headers = {
            'Content-Type': 'application/json',
            }
            json_data = { 
            'name': uploader_name, 'caption': meme_caption, 'url': meme_url
            }
            json_object = json.dumps(json_data, indent=4)  
            response = requests.post('https://meme-zone-v1.herokuapp.com/', headers= headers, data=json_object)
            if another_entry_cb:
                flash("Uploaded Successfully!")
                return redirect(url_for("routes.memes", start_page_var="True"))
            else:
                return redirect(url_for("routes.memes", start_page_var="False"))
        else:
            return render_template("form.html", form=form)
    else:
        if request.args.get('start_page_var')=="True":
            return render_template("form.html", form=form)
        else:
            form = meme_info()
            data_raw = requests.get('https://meme-zone-v1.herokuapp.com/')
            return  render_template("index.html", meme_list=data_raw.json())


@app.route("/about", methods=["GET"])
def about():
    return "<h1>Created with <3 by Krishna Maheshwari!</h1>"


@app.route("/memes/<string:meme_id>", methods=["GET"])
def get_meme_by_id(meme_id):
    meme_info = requests.get('https://meme-zone-v1.herokuapp.com/memes/'+meme_id)
    meme_url = meme_info.json()["meme_url"]
    return "<center> <img src="+ meme_url + " style='width: 100%; height: auto;'></center>"


meme_zone_frontend/templates/form.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block body_attribs %}
style="background-color: tomato"
{% endblock %}

{% block title %} Meme Zone- Upload Meme! {% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href={{ url_for('static', filename='/css/form.css')}}>
{% endblock %}


{% block navbar %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" <a href={{ url_for('routes.start_page') }}>Meme Zone</a>
      </div>
      <ul class="nav navbar-nav">
        <li><a href={{ url_for('routes.memes', start_page_var="False") }}>View Memes</a></li>
      </ul>
      <ul class="nav navbar-nav" style="margin-left: auto;">
        <li><a href="{{ url_for('routes.about') }}">About</a></li>
      </ul>
    </div>
  </nav>
{% endblock %}

{% block content %}

<h1 style="text-align: center; font-weight:bold; font-size:400%;">Meme Zone</h1>
<section class="Form" style="margin-top: 25px;">
    <div class="container">
        <div class="row" style="background: white; border-radius: 30px;">
            <div class="col-lg-5">
                <img src={{ url_for('static', filename='images/undraw_upload.png') }} class="img-fluid" alt="" width="460" height="460" style="border-radius: 30px;">
            </div>
            <div class="col-lg-7" style="padding: 10px 100px;">
                 <h3 style="padding-left: 15px; font-weight: bold;">Upload a meme!</h3>
                 <form action={{ url_for('routes.memes', start_page_var="False") }} method="POST">
                    {{ form.csrf_token }}
                     <div class="form-row">
                         <div class="col-lg-7">
                            {{ wtf.form_field(form.uploader_name, class='form-control', placeholder='Enter you name here') }}
                         </div>
                     </div>
                     <div class="form-row">
                        <div class="col-lg-7">
                            {{ wtf.form_field(form.meme_caption, class='form-control', placeholder='Enter a caption for the meme') }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-7">
                            {{ wtf.form_field(form.meme_url, class='form-control', placeholder='URL for the meme') }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-7">
                            <div class="checkbox">
                                {{ wtf.form_field(form.another_entry_cb, class='form-control') }}
                                <!-- <label><input type="checkbox" value="">Upload another meme</label> -->
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-7">
                            <button type="submit" class="btn1" style="border: none; outline: none; height: 50px; width:100%; font-weight: bold; background-color: black; color: white; border-radius: 5px;">Upload</button>
                        </div>
                    </div>
                 </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

meme_zone_frontend/templates/index.html
{% extends "bootstrap/base.html" %}

{% block body_attribs %}
style="background-color: tomato"
{% endblock %}

{% block title %} Meme Zone- Meme Gallery!  {% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href={{ url_for('static', filename='/css/memes.css')}}>
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" <a href="{{ url_for('routes.start_page') }}">Meme Zone</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a href={{ url_for('routes.memes', start_page_var="True") }}>Upload Meme</a></li>
      </ul>
      <ul class="nav navbar-nav" style="margin-left: auto;">
        <li><a href="{{ url_for('routes.about') }}">About</a></li>
      </ul>
    </div>
  </nav>
{% endblock %}

{% block content %} 
<h1> Meme Gallery</h1>

{% for list_itr in meme_list %}
<div class="gallery" style="float:left; width: 30%; margin: 5px; border: 2px solid black;">
  <a href = {{ url_for('routes.get_meme_by_id', meme_id=list_itr['meme_id']  ) }} target="_blank" alt="">
  <img src="{{ list_itr['meme_url']}}" alt="{{ list_itr['meme_caption'] }}" style="width: 100%; height: auto;">
  </a>
  <div class="meme_details">
    <div>
      {{ list_itr['uploader_name'] }}
    </div>
    <div>
      {{ list_itr['meme_caption'] }}
    </div>
    <div>
      meme_Id: {{ list_itr['meme_id'] }}
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}

meme_zone_frontend/templates/start.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block body_attribs %}
style="background-color: tomato"
{% endblock %}

{% block title %} Meme Zone- Start {% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href={{ url_for('static', filename='/css/start.css')}}>
{% endblock %}

{% block content %}

<h1 style="text-align: center; font-weight:bold; font-size:500%;">Meme Zone</h1>
<section class="Form" style="margin-top: 25px;">
    <form action="" method="POST">
        {{ form.csrf_token }}
        <div class="form-row">
            <div style="padding:0px 100px;">
               <button type="submit" name="submit_btn" value="upload">
                    <img src="{{ url_for('static', filename='images/undraw_upload.png') }}" alt="Save icon" width="460" height="460" style="float: left;" />
                    <br/>
                    <h1>Upload Meme</h1>
                </button>
                <button type="submit" name="submit_btn" value="view">
                    <img src="{{ url_for('static', filename='images/undraw_watch.png') }}" alt="Save icon" width="460" height="460" style="float: right;" />
                    <br/>
                    <h1>View Memes</h1>
                </button>
            </div>
        </div>
    </form>
</section>
{% endblock %}